<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.1" />
  </ItemGroup>



  <ItemGroup>
    <ProjectReference Include="..\NDbUnit.Core\NDbUnit.Core.csproj" />
  </ItemGroup>  
 

</Project>
